### ISSUE TITLE
Wrong entries displayed on macosx

### ISSUE THREAD

**Issue by peterkir** [A7exSchin/EclipseInstallationManager#20]
First image is showing the tray.
Second image shows on left/background the default file layout inside oomph root installation folder.
Top/right finder shows the content of Eclipse App folder from the left.

<img width="204" alt="eim_mac" src="https://github.com/A7exSchin/EclipseInstallationManager/assets/250545/810ed3a7-ba09-47e0-aea9-27797c0bcea7">
<img width="799" alt="eim2_mac" src="https://github.com/A7exSchin/EclipseInstallationManager/assets/250545/ef0e34a5-6d71-442a-afaa-e20861e839a8">

**Comment by A7exSchin** [comment]
Fixed with #24 thanks for the collaboration!
