### ISSUE TITLE
Improve doc for macos - must use vmarg -XstartOnFirstThread

### ISSUE THREAD

**Issue by peterkir** [A7exSchin/EclipseInstallationManager#25]
19:27:15.944 [main] DEBUG tray.impl.TrayApplication - Starting to create UI
***WARNING: Display must be created on main thread due to Cocoa restrictions. Use vmarg -XstartOnFirstThread

**Comment by A7exSchin** [comment]
This argument is included in the `*.bndrun` files for MacOS. Is any other inclusion necessary?

**Comment by A7exSchin** [comment]
Doc is updated, thanks!
