### ISSUE TITLE
Feature Request: enable launching of oomph eclipse installer

### ISSUE THREAD

**Issue by peterkir** [A7exSchin/EclipseInstallationManager#27]
If bootstrap eclipse installer is installed, allow launch from EIM

**Comment by A7exSchin** [comment]
Will be implemented, but probably as one-time configuration where the config data lies in a `~/.eim` folder, as any Eclipse Installer isntallation can be placed anywhere on the system and I haven't found any metadata that suggests where it is installed.

**Comment by A7exSchin** [comment]
Implemented with v0.4.0
