### ISSUE TITLE
Allow additional environment settings for launch

### ISSUE THREAD

**Issue by peterkir** [A7exSchin/EclipseInstallationManager#31]
Allow users to specify additional environment variables for a launch config.
e.g. `HOME=${env.HOME}/customHome;TEMP=${env.TEMP}/otherTemp;FOLDER=${sys.MySystemPropertyKey}`
env is referring to existing environment variables. If not availalble skip it and give WARNING
sys is referring to system properties. If not available skip it and give WARNING

**Comment by A7exSchin** [comment]
Has been added to the features list, but as of now is not on the roadmap.
