### ISSUE TITLE
Bug: Unable to select eclipse installer location  in EIM 0.4.0 on MacOSX x64_64

### ISSUE THREAD

**Issue by peterkir** [A7exSchin/EclipseInstallationManager#32]
Unable to select the eclipse installer.
Neiter the app folder nor the eclipse executable can be selected.

![image](https://github.com/A7exSchin/EclipseInstallationManager/assets/250545/f4d54028-86a1-4c18-a2e0-ea708e1b77f8)

**Comment by A7exSchin** [comment]
Should be fixed with https://github.com/A7exSchin/EclipseInstallationManager/releases/tag/v0.4.1

Can you retest?
